apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-medical
  namespace: medical-app
  labels:
    app: mysql-medical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-medical
  template:
    metadata:
      labels:
        app: mysql-medical
    spec:
      containers:
        - name: mysql-medical
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc